name: node_app

on: # укажите сборку для запуска автоматического ci/cd
  push:
      branches:
          -  "main"

jobs:
  build:
      name: Build Docker image
      runs-on: ubuntu-latest # укажите ОС для работы приложения
      steps:
          - # Клоникуйте код приложения в ОС
              name: Checkout
              uses: actions/checkout@v3
          - # Ввойдите в Docker Hub используя токен
              name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - # Создайте экземпляр build kit builder
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
          - # создайте образ контейнера и отправьте его в Docker Hub с помощью teraclockbox
              name: Build and push
              run: |
                echo "Current working directory: $(pwd)"
                ls -la
                docker buildx version
                docker buildx build \
                  --file /home/gr623-sudev/Dockerfile \
                  --tag ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest \
                  --push /home/gr623-sudev/Dockerfile
